Hotfix footer
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team1 pull request #44
Opened 2022-11-18 15:36 UTC by JoyMarkarian

2022-11-21 08:04 UTC, vassili45 approved these changes

2022-11-22 07:57 UTC, lesylv submitted a review, later dismissed

2022-11-22 08:10 UTC, MartinezEmmanuel03 submitted a review, later dismissed

2022-11-22 08:20 UTC, GuillaumeWernert submitted a review, later dismissed

2022-11-22 08:20 UTC, GuillaumeWernert commented
gg

2022-11-22 08:41 UTC, KevinLavigne requested changes

2022-11-22 08:41 UTC, KevinLavigne commented on frontend/src/components/Footer.jsx
> +          </a>{" "}
espace mort {" "} a suprimer

2022-11-22 08:43 UTC, lesylv approved these changes

2022-11-22 08:44 UTC, MartinezEmmanuel03 approved these changes

2022-11-22 08:46 UTC, KevinLavigne approved these changes

2022-11-22 08:46 UTC, merged